// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztlctqpckcfqwzmmwibs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bGN0cXBja2NmcXd6bW13aWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODc3NzksImV4cCI6MjA2MTM2Mzc3OX0.7qkWXURM4qooqq2reemv4La3_9kGnHx5YPddix90hIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);